/*
 * Program: UI(286) Text Editor
 * Author: Edward Bierens
 * Date Created: Wednesday November 26th, 2025
 * 
 * Description: This is a basic text editor that allows you to display and type text 
 * onto the screen. To create a new line, use the Enter key, and to exist the program, use
 * the key combination Control + S. This software is still in progress; saving and scrolling 
 * are not implemented yet.
 * 
 */

#include <string.h>
#include <textmode.h>
#include <speaker.h>
#include <disk.h>

#undef DATA_SEGMENT
#define DATA_SEGMENT 0x0480 // Data segment value 

// Entry point (do not modify, copy and paste this to the beginning of your program after your includes)
void main();
void __far entrypoint() {

    // Set the data segment
    __asm {
        mov ax, DATA_SEGMENT
        mov ds, ax
    }

    // Call the program's main function
    main();

    // Exit back into the kernel
    return;
}

// Main program code
void main() {

    // Initialize temporary variables (place text buffer at address 0x10000)
    unsigned char x,y,i;
    char c;
    char __far * document = (char __far *) 0x10000000L;
    unsigned short p = 0;
    unsigned short tmp;

    // Initialize window
    TM_BlankScreen(0x30);
    TM_TUIInit("\xDB UI(286) TEXT \xDB", 0x3B);

    // Place corner window characters
    TM_PutChar(0xD5, 0, 1, 0x3E);
    TM_PutChar(0xD4, 0, TM_HEIGHT-2, 0x3E);
    TM_PutChar(0xB8, TM_WIDTH-1, 1, 0x3E);
    TM_PutChar(0xBE, TM_WIDTH-1, TM_HEIGHT-2, 0x3E);

    // Draw horizontal window lines
    for (x = 1; x < TM_WIDTH-1; x++) {
        TM_PutChar(0xCD, x, 1, 0x3E);
        TM_PutChar(0xCD, x, TM_HEIGHT-2, 0x3E);
    }

    // Draw vertical window lines
    for (y = 2; y < TM_HEIGHT-2; y++) {
        TM_PutChar(0xB3, 0, y, 0x3E);
        TM_PutChar(0xB3, TM_WIDTH-1, y, 0x3E);
    }

    // Go to the beginning line of the text editor
    TM_SetCursor(1, 2);
    x = 1;
    y = 2;

    // Get characters and determine
    do {

        // Get character
        c = GetChar_H();

        // Enable backspace functionality
        if (c == 0x8) {

            // Beep and do nothing else if at the very beginning
            if (p == 0) {
                beep(1046, 25000);
                beep(1196, 25000);
                beep(1046, 25000);
                continue;
            }

            // "Delete" last character
            p--;

            // Determine if at beginning of new row
            if (x == 1) {

                // Determine if on first row 
                if (y == 2) {

                    // Temporary code (will beep)
                    beep(1046, 25000);
                    beep(1196, 25000);
                    beep(1046, 25000);
                    continue;

                } else { // Not on first row (go back to previous line)

                    // Otherwise go back one row and go to end of line
                    y--;
                    x = TM_WIDTH-2;

                    // Decrease current X coordinate until it reaches beginning or finds end of the line on display
                    TM_ClearChar(x, y, 0x3E);
                    while (TM_PeekChar(x-1,y) == 0 && x > 1) {
                        x--;
                    }

                }

            // If not at beginning of line, just clear the current character and go back
            } else {
                x--;
                TM_ClearChar(x, y, 0x3E);
            }

            // Reset Cursor and continue
            TM_SetCursor(x, y);
            continue;

        }

        // Determine whether new line is needed
        if (c == 0xD || x == TM_WIDTH-1) {
            if (c == 0xD) document[p] = 0xA;
            x = 1;
            y++;
        }

        // Print out character 
        if (c != 0xD) {
            document[p] = c;
            TM_PutChar(c, x, y, 0x3F);
            x++;
        }

        // Reset Cursor and increase index
        TM_SetCursor(x, y);
        p++;

    } while (c != 0x18); // Reserve the character generated by Control + S for exiting the software

}
