/*
 * Program: UI(286) Text Editor
 * Author: Edward Bierens
 * Date Created: Wednesday November 26th, 2025
 * 
 * Description: This is a basic text editor that allows you to display and type text 
 * onto the screen. To create a new line, use the Enter key, and to exist the program, use
 * the key combination Control + S. This software is still in progress; saving and scrolling 
 * are not implemented yet.
 * 
 */

#include <string.h>
#include <textmode.h>
#include <speaker.h>

// Entry point (do not modify, copy and paste this to the beginning of your program after your includes)
void main();
void __far entrypoint() {

    // Set the data segment
    __asm {
        mov ax, 0x1500
        mov ds, ax
    }

    // Call the program's main function
    main();

    // Exit back into the kernel
    return;
}

// Main program code
void main() {

    // Initialize temporary variables
    unsigned char x,y,i;
    char c;

    // Initialize window
    TM_BlankScreen(0x30);
    TM_TUIInit("\xDB UI(286) TEXT \xDB", 0x3B);

    // Place corner window characters
    TM_PutChar(0xD5, 0, 1, 0x3E);
    TM_PutChar(0xD4, 0, TM_HEIGHT-2, 0x3E);
    TM_PutChar(0xB8, TM_WIDTH-1, 1, 0x3E);
    TM_PutChar(0xBE, TM_WIDTH-1, TM_HEIGHT-2, 0x3E);

    // Draw horizontal window lines
    for (x = 1; x < TM_WIDTH-1; x++) {
        TM_PutChar(0xCD, x, 1, 0x3E);
        TM_PutChar(0xCD, x, TM_HEIGHT-2, 0x3E);
    }

    // Draw vertical window lines
    for (y = 2; y < TM_HEIGHT-2; y++) {
        TM_PutChar(0xB3, 0, y, 0x3E);
        TM_PutChar(0xB3, TM_WIDTH-1, y, 0x3E);
    }

    // Go to where the text editing would begin
    TM_SetCursor(1, 2);
    x = 1;
    y = 2;

    // Get characters and determine
    do {

        // Get character
        c = GetChar_H();

        // Determine whether new line is needed
        if (c == 0xD || x == TM_WIDTH-2) {
            x = 1;
            y++;
        }

        // Print out character 
        if (c != 0xD) {
            TM_PutChar(c, x, y, 0x3F);
            x++;
        }

    } while (c != 0x13); // Reserve the character generated by Control + S for exiting the software

}
